# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: hyperping_exporter
    binary: hyperping_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
      - 8

docker_manifests:
  - name_template: "docker.io/samber/hyperping-exporter:{{ .Tag }}"
    image_templates:
      - "docker.io/samber/hyperping-exporter:{{ .Tag }}-amd64"
      - "docker.io/samber/hyperping-exporter:{{ .Tag }}-arm64"

dockers:
  - image_templates:
      - "docker.io/samber/hyperping-exporter:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    # build_flag_templates:
    #   - "--pull"
    #   - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - "docker.io/samber/hyperping-exporter:{{ .Tag }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    # build_flag_templates:
    #   - "--pull"
    #   - "--platform=linux/arm64"
    goarch: arm64

archives:
  - id: binary
    format: binary
    # name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}"
  - id: archive
    format: tar.gz
    # name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
